(() => {
  'use strict';
  const cfg = window.SMB_CONFIG || {};
  const sbReady = cfg.SUPABASE_URL?.startsWith('https://') && cfg.SUPABASE_PUBLISHABLE_KEY && !cfg.SUPABASE_URL.includes('YOUR-PROJECT') && !cfg.SUPABASE_PUBLISHABLE_KEY.includes('YOUR_');
  const supabase = sbReady ? window.supabase.createClient(cfg.SUPABASE_URL, cfg.SUPABASE_PUBLISHABLE_KEY, { auth: { persistSession: true, autoRefreshToken: true, detectSessionInUrl: true } }) : null;
  const $ = (s,root=document) => root.querySelector(s);
  const $$ = (s,root=document) => [...root.querySelectorAll(s)];
  const state = { session:null, profile:null, tryouts:[], quizHistory:[], activeSubtest:null };

  const data = {
    'logika-fundamental': {badge:'Materi Fundamental', title:'Logika Fundamental', subtitle:'Penalaran & pemecahan masalah', desc:'Bangun kemampuan menarik kesimpulan, membaca pola, dan menguji argumen secara runtut.', topics:['Silogisme','Analogi','Induktif','Deduktif'], quiz:[['Semua siswa rajin lulus. Sebagian pejuang UTBK rajin. Kesimpulan paling tepat?', ['Sebagian pejuang UTBK lulus','Semua pejuang UTBK lulus','Tidak ada yang lulus','Semua siswa adalah pejuang UTBK'],0],['Jika A > B dan B > C, maka...', ['A < C','A = C','A > C','Tidak dapat ditentukan'],2]], materi:'https://youtube.com/playlist?list=PLPtbHTXes2LPnITvrZvQ_yR5FnY6TTFiU', soal:'https://drive.google.com/drive/folders/1Mm3qSaIDLL20rm5PtrqhZRiF-9tJb3D7'},
    'matematika-fundamental': {badge:'Materi Fundamental', title:'Matematika Fundamental', subtitle:'Aljabar, aritmetika, geometri', desc:'Pahami konsep inti matematika sebelum masuk soal kompleks dan HOTS.', topics:['Aljabar','Aritmetika','Geometri','Fungsi'], quiz:[['Jika 2^(x+1)=16, nilai x?', ['2','3','4','5'],1],['Diskon 20% membuat harga menjadi Rp80.000. Harga awal?', ['90.000','100.000','110.000','120.000'],1]], materi:'https://youtube.com/playlist?list=PLPtbHTXes2LPJDunxjBOU0knXcBhbvJ1G', soal:'https://drive.google.com/drive/folders/1VIHyDWl7EFmqVQ0grjufG_YxumsP4X19'},
    'indonesia-fundamental': {badge:'Materi Fundamental', title:'Bahasa Indonesia Fundamental', subtitle:'Ejaan, kalimat efektif, teks', desc:'Perkuat dasar ejaan, struktur kalimat, dan analisis bacaan.', topics:['EBI','Kalimat Efektif','Ide Pokok','Konjungsi'], quiz:[['Manakah penulisan kata baku yang tepat?', ['Apotik','Apotek','Apoteke','Apotick'],1]], materi:'https://www.youtube.com/playlist?list=PLPtbHTXes2LPrYPjxuqNvKN-HyIMPf3ts', soal:'https://drive.google.com/drive/folders/1PpouuntwzVL7tUySNt95LofoeVXow8di'},
    'inggris-fundamental': {badge:'Materi Fundamental', title:'Bahasa Inggris Fundamental', subtitle:'Reading comprehension & grammar', desc:'Bangun fondasi reading, grammar, vocabulary, dan inference.', topics:['Main Idea','Grammar','Vocabulary','Inference'], quiz:[['Synonym of “Crucial” is...', ['Trivial','Vital','Minor','Optional'],1]], materi:null, soal:'https://drive.google.com/drive/folders/1Yry1TGGUXTvNa5byBchWUUw0pKjseOgz'},
    'pu-subtest': {badge:'Subtes TPS', title:'Penalaran Umum (PU)', subtitle:'Logika, analisis, penalaran', desc:'Latih penalaran induktif, deduktif, dan kuantitatif.', topics:['Induktif','Deduktif','Kuantitatif','Silogisme'], quiz:[['Pola 2,4,8,16,... berikutnya?', ['24','30','32','64'],2]], materi:'https://youtube.com/playlist?list=PLPtbHTXes2LNXEln1sgp7UlJrlIeTDogq', soal:'https://drive.google.com/drive/folders/1Ckq7yGqrJY1yiLOzaq1d6iGQYeo__QMG'},
    'ppu-subtest': {badge:'Subtes TPS', title:'Pengetahuan & Pemahaman Umum (PPU)', subtitle:'Makna kata & hubungan gagasan', desc:'Uji pemahaman kata, istilah, hubungan ide, dan pesan tertulis.', topics:['Makna Kata','Sinonim','Antonim','Wawasan'], quiz:[['Sinonim “efektif” dalam belajar?', ['Cepat','Tepat guna','Hemat','Banyak'],1]], materi:null, soal:'https://drive.google.com/drive/folders/1U36MRMR6VnNLbs1NCYaXMoKM-N_gti-f'},
    'pbm-subtest': {badge:'Subtes TPS', title:'Pemahaman Bacaan & Menulis (PBM)', subtitle:'Bacaan & kaidah penulisan', desc:'Fokus pada ejaan, struktur kalimat, konjungsi, dan kepaduan paragraf.', topics:['EBI','Konjungsi','Paragraf','Kepaduan'], quiz:[['Konjungsi yang menyatakan pertentangan?', ['Dan','Namun','Sehingga','Karena'],1]], materi:null, soal:'https://drive.google.com/drive/folders/1PezGd21KY-8d4RhqWWSvV6qwfOJysrt1'},
    'pk-subtest': {badge:'Subtes TPS', title:'Pengetahuan Kuantitatif (PK)', subtitle:'Matematika, data, peluang', desc:'Latih aljabar, geometri, statistika, peluang, dan kecukupan data.', topics:['Aljabar','Geometri','Statistika','Peluang'], quiz:[['Rata-rata 10,20,x adalah 20. x = ?', ['20','30','40','10'],1]], materi:'https://youtube.com/playlist?list=PLPtbHTXes2LODiuJ0tHgrIMLeozqQakGM', soal:'https://drive.google.com/drive/folders/1N0QlQT5ej12YfRDlUI6njf3r_q3G7zCo'},
    'lit-indo-subtest': {badge:'Subtes Literasi', title:'Literasi Bahasa Indonesia', subtitle:'Analisis teks & kesimpulan', desc:'Baca kritis, identifikasi fakta/opini, gagasan utama, dan inferensi.', topics:['Teks Kompleks','Gagasan Utama','Simpulan','Argumen'], quiz:[['Gagasan utama paragraf biasanya dapat ditemukan di...', ['Awal/akhir','Tengah','Luar teks','Hanya judul'],0]], materi:'https://youtube.com/playlist?list=PLPtbHTXes2LPdFISsxrircxNkJZ4DTKuz', soal:'https://drive.google.com/drive/folders/1wTb0dE6rqRbX4GkcsoxCh-urDcWXl1vE'},
    'lit-inggris-subtest': {badge:'Subtes Literasi', title:'Literasi Bahasa Inggris', subtitle:'Academic reading skills', desc:'Fokus pada main idea, tone, purpose, inference, dan vocabulary konteks.', topics:['Main Idea','Tone','Purpose','Inference'], quiz:[['Primary purpose of an academic text?', ['To entertain','To inform and argue','To sell products','To confuse readers'],1]], materi:'https://youtube.com/playlist?list=PLPtbHTXes2LOLIOQLMhkmiQ3H99DwL1_n', soal:'https://drive.google.com/drive/folders/1IUqQxo6jqJKR3fZ18TxMHWEJj4gA8Xza'},
    'pm-subtest': {badge:'Subtes Literasi', title:'Penalaran Matematika (PM)', subtitle:'Modeling masalah nyata', desc:'Ubah situasi sehari-hari menjadi model matematika dan selesaikan secara runtut.', topics:['Soal Cerita','Model Matematika','Grafik','Optimasi'], quiz:[['Kecepatan 60 km/jam selama 2 jam menempuh jarak...', ['100 km','120 km','140 km','80 km'],1]], materi:'https://youtube.com/playlist?list=PLPtbHTXes2LOPt4mtAcQwbWpD2y1QLJdr', soal:'https://drive.google.com/drive/folders/1j5y_zsoa4QoA6AgATzl1WiJqZHPlSm9_'}
  };

  const faq = [
    ['Apakah komunitas gratis?','Sebagian besar materi dan kanal komunitas dapat diakses gratis. Fitur akun hanya menambah penyimpanan progres personal.'],
    ['Apakah data tracker tersimpan di browser?','Versi ini menyimpan tryout di database Supabase berdasarkan akun.'],
    ['Apakah kalkulator menjamin lolos PTN?','Tidak. Kalkulator hanya simulasi target internal, bukan prediksi resmi kelulusan.']
  ];

  function toast(msg,type='ok'){const el=$('#toast');el.textContent=msg;el.className='fixed top-24 right-4 z-[100] max-w-sm rounded-2xl px-4 py-3 text-sm font-bold shadow-2xl '+(type==='error'?'bg-red-600 text-white':'bg-pine-900 text-white');el.classList.remove('hidden');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.add('hidden'),3200)}
  function showPage(name){$$('[data-page]').forEach(x=>x.classList.add('hidden'));$(`#view-${name}`).classList.remove('hidden');window.scrollTo({top:0,behavior:'smooth'});closeMobile()}
  function closeMobile(){$('#mobileMenu').classList.add('hidden');$('#mobileBtn').setAttribute('aria-expanded','false')}
  function openModal(id){const el=$(`#${id}`);el.classList.remove('hidden');el.classList.add('flex');document.body.classList.add('lock-scroll')}
  function closeModal(id){const el=$(`#${id}`);el.classList.add('hidden');el.classList.remove('flex');document.body.classList.remove('lock-scroll')}
  function escapeHtml(v){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}

  function renderCards(){
    $('#fundamentalGrid').innerHTML=['logika-fundamental','matematika-fundamental','indonesia-fundamental','inggris-fundamental'].map(k=>cardHtml(k)).join('');
    $('#subtestGrid').innerHTML=['pu-subtest','ppu-subtest','pbm-subtest','pk-subtest','lit-indo-subtest','lit-inggris-subtest','pm-subtest'].map(k=>cardHtml(k)).join('');
    $('#faqList').innerHTML=faq.map(([q,a],i)=>`<div class="glass rounded-2xl overflow-hidden"><button data-faq="${i}" class="w-full flex justify-between gap-4 items-center text-left px-5 py-4 font-extrabold focus-ring"><span>${escapeHtml(q)}</span><span>+</span></button><div id="faq-${i}" class="hidden px-5 pb-5 text-sm font-semibold opacity-80">${escapeHtml(a)}</div></div>`).join('');
  }
  function cardHtml(k){const d=data[k];return `<button data-subtest="${escapeHtml(k)}" class="glass rounded-2xl p-6 text-left btn focus-ring"><div class="text-xs font-mono font-extrabold uppercase opacity-60">${escapeHtml(d.badge)}</div><h3 class="mt-2 text-xl font-black">${escapeHtml(d.title)}</h3><p class="mt-2 text-sm font-semibold opacity-80">${escapeHtml(d.subtitle)}</p><div class="mt-5 pt-4 border-t border-pine-500/15 text-xs font-extrabold text-emeraldCustom-700 dark:text-emeraldCustom-400">Buka modul & quiz →</div></button>`}

  function openSubtest(k){state.activeSubtest=k;const d=data[k];$('#detailBadge').textContent=d.badge;$('#detailTitle').textContent=d.title;$('#detailSubtitle').textContent=d.subtitle;$('#detailDesc').textContent=d.desc;$('#detailTopics').innerHTML=d.topics.map(t=>`<span class="px-3 py-1.5 rounded-lg bg-emeraldCustom-500/10 border border-emeraldCustom-500/20 text-xs font-bold">${escapeHtml(t)}</span>`).join('');$('#detailOpenBtn').onclick=()=>{closeModal('detailModal');renderSubtest(k);};openModal('detailModal')}
  function renderSubtest(k){showPage('subtest');const d=data[k];const qs=d.quiz||[];$('#subtestContent').innerHTML=`<div class="glass rounded-3xl p-7 sm:p-9"><div class="text-xs font-mono font-extrabold opacity-60">${escapeHtml(d.badge)}</div><h1 class="text-4xl sm:text-5xl font-black mt-1">${escapeHtml(d.title)}</h1><p class="mt-3 text-lg font-extrabold text-emeraldCustom-700 dark:text-emeraldCustom-400">${escapeHtml(d.subtitle)}</p><p class="mt-5 text-sm sm:text-base font-semibold leading-relaxed opacity-85">${escapeHtml(d.desc)}</p><div class="flex flex-wrap gap-2 mt-6">${d.topics.map(t=>`<span class="px-3 py-1.5 rounded-xl bg-pine-500/10 text-xs font-bold">${escapeHtml(t)}</span>`).join('')}</div><div class="grid md:grid-cols-2 gap-4 mt-8">${d.materi?`<a target="_blank" rel="noopener noreferrer" href="${d.materi}" class="btn rounded-2xl bg-gradient-to-r from-emeraldCustom-600 to-pine-800 text-white p-5 font-extrabold">📺 Buka Playlist YouTube</a>`:`<div class="rounded-2xl p-5 bg-pine-500/10 font-extrabold">🎬 Video materi sedang disiapkan</div>`}<a target="_blank" rel="noopener noreferrer" href="${d.soal}" class="btn rounded-2xl bg-pine-900 text-white p-5 font-extrabold">📂 Buka Folder Soal</a></div></div><div class="glass rounded-3xl p-7 sm:p-9 mt-6"><div class="text-xs font-mono font-extrabold uppercase text-emeraldCustom-700">Pop-Quiz Interaktif</div><h2 class="text-2xl font-black mt-1">Uji pemahaman</h2><div id="quizBox" class="space-y-5 mt-6">${qs.map((q,i)=>`<div class="rounded-2xl p-5 bg-pine-500/5"><p class="font-extrabold">${i+1}. ${escapeHtml(q[0])}</p><div class="grid sm:grid-cols-2 gap-2 mt-3">${q[1].map((o,j)=>`<button type="button" class="quizOpt btn rounded-xl border border-pine-500/20 p-3 text-left text-sm font-bold focus-ring" data-q="${i}" data-a="${j}">${escapeHtml(o)}</button>`).join('')}</div></div>`).join('')}</div><div id="quizScore" class="hidden mt-6 rounded-2xl p-5 bg-emeraldCustom-500/10 text-center font-black"></div></div>`;initQuiz(k)}
  function initQuiz(k){const d=data[k];let answers=new Map();$$('.quizOpt').forEach(btn=>btn.addEventListener('click',()=>{const q=Number(btn.dataset.q),a=Number(btn.dataset.a);if(answers.has(q))return;answers.set(q,a);const all=$$(`.quizOpt[data-q="${q}"]`);all.forEach(x=>x.disabled=true);const correct=d.quiz[q][2];all[correct].classList.add('bg-emeraldCustom-600','text-white');if(a!==correct)btn.classList.add('bg-red-600','text-white');if(answers.size===d.quiz.length){const score=[...answers].filter(([qi,ai])=>ai===d.quiz[qi][2]).length;const pct=Math.round(score/d.quiz.length*100);const el=$('#quizScore');el.textContent=`Skor ${score}/${d.quiz.length} · Akurasi ${pct}%`;el.classList.remove('hidden');saveQuizAttempt(k,score,d.quiz.length)}}))}

  async function currentUser(){if(!supabase)return null;const {data,error}=await supabase.auth.getSession();if(error){console.error(error);return null}state.session=data.session;return data.session?.user||null}
  async function ensureProfile(user){if(!supabase||!user)return;const {data:p}=await supabase.from('profiles').select('*').eq('id',user.id).maybeSingle();if(!p)await supabase.from('profiles').insert({id:user.id,display_name:user.user_metadata?.display_name||'Pejuang PTN'});state.profile=p||{id:user.id,display_name:user.user_metadata?.display_name||'Pejuang PTN'} }
  async function refreshBackend(){const user=await currentUser();if(!user){updateAuthUi(null);return}await ensureProfile(user);const [{data:t,error:te},{data:q,error:qe},{data:p,error:pe}]=await Promise.all([supabase.from('tryout_attempts').select('*').order('taken_on',{ascending:true}).order('created_at',{ascending:true}),supabase.from('quiz_attempts').select('*').order('created_at',{ascending:false}).limit(25),supabase.from('profiles').select('*').eq('id',user.id).maybeSingle()]);if(te||qe||pe){console.error(te||qe||pe);toast('Gagal mengambil data akun. Cek RLS/schema Supabase.','error');return}state.tryouts=t||[];state.quizHistory=q||[];state.profile=p||state.profile;updateAuthUi(user);renderTracker();renderDashboard()}
  function updateAuthUi(user){const btn=$('#authBtn');if(user){btn.textContent=state.profile?.display_name?`👤 ${state.profile.display_name}`:'Dashboard';btn.onclick=()=>showPage('dashboard');$('#trackerAuthState').textContent=user.is_anonymous?'Mode tamu':'Tersimpan di cloud';}else{btn.textContent='Masuk';btn.onclick=()=>openModal('authModal');$('#trackerAuthState').textContent='Belum masuk'}}
  async function authLogin(){if(!supabase)return setupMissing();const email=$('#authEmail').value.trim();const password=$('#authPassword').value;if(!email||password.length<6)return toast('Email/password belum valid.','error');const {error}=await supabase.auth.signInWithPassword({email,password});if(error)return toast(error.message,'error');closeModal('authModal');await refreshBackend();toast('Berhasil masuk.')}
  async function authRegister(){if(!supabase)return setupMissing();const email=$('#authEmail').value.trim();const password=$('#authPassword').value;if(!email||password.length<6)return toast('Gunakan email valid dan password minimal 6 karakter.','error');const {data:d,error}=await supabase.auth.signUp({email,password});if(error)return toast(error.message,'error');if(d.session){closeModal('authModal');await refreshBackend();toast('Akun berhasil dibuat.')}else toast('Akun dibuat. Cek email untuk verifikasi.')} 
  async function authGuest(){if(!supabase)return setupMissing();const {error}=await supabase.auth.signInAnonymously();if(error)return toast(error.message,'error');closeModal('authModal');await refreshBackend();toast('Masuk sebagai tamu. Progres tersimpan di browser akun ini.')}
  async function signOut(){if(!supabase)return;const {error}=await supabase.auth.signOut();if(error)return toast(error.message,'error');state.session=null;state.profile=null;state.tryouts=[];state.quizHistory=[];updateAuthUi(null);showPage('landing');toast('Kamu sudah keluar.')}
  async function saveProfile(e){e.preventDefault();if(!supabase||!state.session?.user)return openModal('authModal');const payload={id:state.session.user.id,display_name:$('#profileName').value.trim()||'Pejuang PTN',target_ptn:$('#profilePtn').value.trim()||null,target_major:$('#profileMajor').value.trim()||null,target_score:$('#profileScore').value?Number($('#profileScore').value):null,updated_at:new Date().toISOString()};if(payload.target_score!==null&&(!Number.isFinite(payload.target_score)||payload.target_score<0||payload.target_score>1000))return toast('Target skor harus 0–1000.','error');const {data:p,error}=await supabase.from('profiles').upsert(payload).select().single();if(error)return toast(error.message,'error');state.profile=p;updateAuthUi(state.session.user);renderDashboard();toast('Profil diperbarui.')}
  async function saveTracker(e){e.preventDefault();if(!supabase||!state.session?.user)return openModal('authModal');const name=$('#toName').value.trim();const score=Number($('#toScore').value);const date=$('#toDate').value;if(!name||name.length>80||!Number.isFinite(score)||score<0||score>1000||!date)return toast('Isi tracker dengan benar.','error');const {error}=await supabase.from('tryout_attempts').insert({user_id:state.session.user.id,name,score,taken_on:date});if(error)return toast(error.message,'error');$('#trackerForm').reset();await refreshBackend();toast('Tryout tersimpan ke database.')}
  async function deleteTracker(id){if(!supabase||!state.session?.user)return;const {error}=await supabase.from('tryout_attempts').delete().eq('id',id);if(error)return toast(error.message,'error');state.tryouts=state.tryouts.filter(x=>x.id!==id);renderTracker();renderDashboard();toast('Catatan dihapus.')}
  async function saveQuizAttempt(k,score,total){if(!supabase||!state.session?.user)return;const {error}=await supabase.from('quiz_attempts').insert({user_id:state.session.user.id,quiz_key:k,score,total});if(error)console.error(error);else{state.quizHistory.unshift({quiz_key:k,score,total,accuracy:score/total*100,created_at:new Date().toISOString()});renderDashboard()}}

  function renderTracker(){const rows=$('#trackerRows');const sorted=[...state.tryouts].sort((a,b)=>new Date(a.taken_on)-new Date(b.taken_on));rows.innerHTML=sorted.length?sorted.map(x=>`<tr class="border-b border-pine-500/10"><td class="px-3 py-3 font-mono text-xs">${escapeHtml(x.taken_on)}</td><td class="px-3 py-3 font-bold">${escapeHtml(x.name)}</td><td class="px-3 py-3 font-black text-emeraldCustom-700 dark:text-emeraldCustom-400">${Number(x.score).toFixed(2).replace(/\.00$/,'')}</td><td class="px-3 py-3 text-right"><button data-del="${escapeHtml(x.id)}" class="text-xs font-extrabold text-red-600 focus-ring">Hapus</button></td></tr>`).join(''):`<tr><td colspan="4" class="px-3 py-10 text-center font-bold opacity-60">Belum ada data tryout.</td></tr>`;$$('[data-del]').forEach(b=>b.addEventListener('click',()=>deleteTracker(b.dataset.del)));const best=state.tryouts.length?Math.max(...state.tryouts.map(x=>Number(x.score))):0;$('#trackerBest').textContent=best?`Best: ${best}`:'';drawProgress(sorted)}
  function drawProgress(items){const c=$('#progressCanvas'),ctx=c.getContext('2d'),w=c.clientWidth||800,h=220,dpr=window.devicePixelRatio||1;c.width=w*dpr;c.height=h*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);ctx.font='12px JetBrains Mono';if(!items.length){ctx.fillStyle=getCss('--muted');ctx.fillText('Tambahkan tryout untuk melihat grafik.',20,40);return}const pad={l:45,r:20,t:20,b:30},iw=w-pad.l-pad.r,ih=h-pad.t-pad.b;const min=Math.max(0,Math.floor(Math.min(...items.map(x=>Number(x.score)))/50)*50),max=Math.min(1000,Math.ceil(Math.max(...items.map(x=>Number(x.score)))/50)*50||1000);const x=i=>pad.l+(items.length===1?iw/2:iw*i/(items.length-1));const y=s=>pad.t+ih-(s-min)/(Math.max(1,max-min))*ih;ctx.strokeStyle=getCss('--border');ctx.lineWidth=1;[min,(min+max)/2,max].forEach(v=>{ctx.beginPath();ctx.moveTo(pad.l,y(v));ctx.lineTo(w-pad.r,y(v));ctx.stroke();ctx.fillStyle=getCss('--muted');ctx.fillText(Math.round(v),5,y(v)+4)});ctx.beginPath();items.forEach((it,i)=>{const xx=x(i),yy=y(Number(it.score));i?ctx.lineTo(xx,yy):ctx.moveTo(xx,yy)});ctx.strokeStyle='#059669';ctx.lineWidth=3;ctx.stroke();items.forEach((it,i)=>{const xx=x(i),yy=y(Number(it.score));ctx.beginPath();ctx.arc(xx,yy,4,0,Math.PI*2);ctx.fillStyle='#10B981';ctx.fill();ctx.fillStyle=getCss('--muted');ctx.fillText(String(Number(it.score).toFixed(0)),xx-10,yy-10)})}
  function getCss(v){return getComputedStyle(document.documentElement).getPropertyValue(v).trim()||'#6B7280'}
  function renderDashboard(){const u=state.session?.user;if(!u)return;const p=state.profile||{};$('#dashName').textContent=p.display_name||'Pejuang PTN';$('#dashEmail').textContent=u.is_anonymous?'Akun tamu':'Email: '+(u.email||'');$('#dashTryoutCount').textContent=state.tryouts.length;$('#dashBest').textContent=state.tryouts.length?Math.max(...state.tryouts.map(x=>Number(x.score))).toFixed(0):'0';$('#dashQuizCount').textContent=state.quizHistory.length;$('#profileName').value=p.display_name||'';$('#profilePtn').value=p.target_ptn||'';$('#profileMajor').value=p.target_major||'';$('#profileScore').value=p.target_score??'';const q=$('#quizHistory');q.innerHTML=state.quizHistory.length?state.quizHistory.map(x=>`<div class="glass rounded-xl p-4 flex justify-between gap-4"><span class="text-sm font-bold">${escapeHtml(data[x.quiz_key]?.title||x.quiz_key)}</span><span class="text-xs font-mono font-extrabold">${x.score}/${x.total} · ${Number(x.accuracy).toFixed(0)}%</span></div>`).join(''):`<div class="text-sm font-bold opacity-60">Belum ada histori quiz.</div>`}
  function calcScores(){const fields=['PU','PPU','PBM','PK','BI','BE','PM'];const vals=[];for(const f of fields){const v=Number($(`#score-${f}`).value);if(!Number.isFinite(v)||v<0||v>1000)return toast('Semua nilai harus diisi antara 0–1000.','error');vals.push(v)}const avg=Math.round(vals.reduce((a,b)=>a+b,0)/vals.length);$('#avgScore').textContent=avg;$('#avgLabel').textContent=avg>=720?'Target tinggi. Gunakan sebagai target belajar, bukan jaminan kelulusan.':avg>=650?'Target kompetitif. Fokus naikkan konsistensi.':'Target masih perlu diperkuat. Bangun konsep dan latihan bertahap.';$('#calcResult').classList.remove('hidden')}
  function setupCalculator(){$('#scoreForm').innerHTML=[['PU','Penalaran Umum'],['PPU','Pengetahuan & Pemahaman'],['PBM','Pemahaman Bacaan & Menulis'],['PK','Pengetahuan Kuantitatif'],['BI','Literasi B. Indonesia'],['BE','Literasi B. Inggris'],['PM','Penalaran Matematika']].map(([id,l])=>`<label class="text-sm font-bold">${l}<input id="score-${id}" type="number" min="0" max="1000" required class="focus-ring mt-1 w-full rounded-xl border border-pine-500/20 bg-white dark:bg-iceblue-900/90 px-4 py-2.5" placeholder="700"></label>`).join('')}
  function setupEvents(){document.addEventListener('click',e=>{const view=e.target.closest('[data-view]');if(view){e.preventDefault();showPage(view.dataset.view||'landing');if(view.dataset.scroll){setTimeout(()=>document.getElementById(view.dataset.scroll)?.scrollIntoView({behavior:'smooth'}),30)}}const pg=e.target.closest('[data-open-page]');if(pg)showPage(pg.dataset.openPage);const st=e.target.closest('[data-subtest]');if(st)openSubtest(st.dataset.subtest);const faqBtn=e.target.closest('[data-faq]');if(faqBtn){const i=faqBtn.dataset.faq;const panel=$(`#faq-${i}`);const hidden=panel.classList.contains('hidden');$$('[id^="faq-"]').forEach(x=>x.classList.add('hidden'));panel.classList.toggle('hidden',!hidden);$$('[data-faq]').forEach(b=>b.lastElementChild.textContent='+');faqBtn.lastElementChild.textContent=hidden?'−':'+'}const close=e.target.closest('[data-close-modal]');if(close)closeModal(close.dataset.closeModal)});
    $('#themeBtn').addEventListener('click',()=>{document.documentElement.classList.toggle('dark');document.documentElement.classList.toggle('light');localStorage.setItem('smb_theme',document.documentElement.classList.contains('dark')?'dark':'light');$('#themeBtn').textContent=document.documentElement.classList.contains('dark')?'☀️':'🌙';drawProgress([...state.tryouts].sort((a,b)=>new Date(a.taken_on)-new Date(b.taken_on)))});
    $('#mobileBtn').addEventListener('click',()=>{const open=!$('#mobileMenu').classList.contains('hidden');$('#mobileMenu').classList.toggle('hidden');$('#mobileBtn').setAttribute('aria-expanded',String(!open))});
    $('#authForm').addEventListener('submit',e=>{e.preventDefault();authLogin()});$('#registerBtn').addEventListener('click',authRegister);$('#guestBtn').addEventListener('click',authGuest);$('#trackerForm').addEventListener('submit',saveTracker);$('#profileForm').addEventListener('submit',saveProfile);$('#calcBtn').addEventListener('click',calcScores);$('#signOutBtn').addEventListener('click',signOut);
    $$('.custom-cursor,a,button,input').forEach(el=>{el.addEventListener('mouseenter',()=>document.body.classList.add('cursor-hover'));el.addEventListener('mouseleave',()=>document.body.classList.remove('cursor-hover'))});
    document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeModal('authModal');closeModal('detailModal')}});window.addEventListener('resize',()=>drawProgress([...state.tryouts].sort((a,b)=>new Date(a.taken_on)-new Date(b.taken_on))));
  }
  function startCountdown(){const target=new Date('2027-04-22T07:30:00+07:00').getTime();setInterval(()=>{const d=Math.max(0,target-Date.now());$('#cdD').textContent=String(Math.floor(d/86400000)).padStart(2,'0');$('#cdH').textContent=String(Math.floor(d%86400000/3600000)).padStart(2,'0');$('#cdM').textContent=String(Math.floor(d%3600000/60000)).padStart(2,'0');$('#cdS').textContent=String(Math.floor(d%60000/1000)).padStart(2,'0')},1000)}
  function setupMissing(){toast('Backend belum dikonfigurasi. Isi js/config.js dengan URL dan publishable key Supabase.','error');openModal('authModal')}
  async function boot(){renderCards();setupCalculator();setupEvents();startCountdown();const theme=localStorage.getItem('smb_theme');if(theme==='dark'){document.documentElement.classList.add('dark');document.documentElement.classList.remove('light');$('#themeBtn').textContent='☀️'}if(supabase){supabase.auth.onAuthStateChange(async()=>{setTimeout(refreshBackend,0)});await refreshBackend()}else updateAuthUi(null);let n=0;const timer=setInterval(()=>{$('#loadPct').textContent=(n+=10)+'%';if(n>=100){clearInterval(timer);$('#loader').style.display='none'}},70)}
  boot();
})();
